/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Usuario.UsuarioTableModel;
import aluno.Aluno;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import usuario.Usuario;
import usuario.UsuarioDAO;

/**
 *
 * @author ALCIOMAR
 */
public class CadastrarUsuario extends javax.swing.JDialog {

    Usuario usuario = new Usuario();
    UsuarioDAO dao = new UsuarioDAO();

    public void limparCampos() {
        util.Util.limparCamposJDialog(this);
        usuario = new Usuario();
        Excluir.setEnabled(false);
    }

    /**
     * Creates new form CadastrarUsuarioo
     */
    public CadastrarUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Excluir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Limpar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Pesquisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Excluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfLogin = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        tfSenha = new javax.swing.JPasswordField();
        SalvarUsuario = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        cargo = new javax.swing.JComboBox<>();
        transparencia = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(537, 349));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(537, 349));
        getContentPane().setLayout(null);

        Limpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/LIMPAR_1.png"))); // NOI18N
        Limpar.setBorderPainted(false);
        Limpar.setContentAreaFilled(false);
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });
        getContentPane().add(Limpar);
        Limpar.setBounds(30, 250, 120, 39);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CADASTRO DE USUARIO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 10, 250, 27);

        Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/PESQUISAR_1.png"))); // NOI18N
        Pesquisar.setBorderPainted(false);
        Pesquisar.setContentAreaFilled(false);
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(Pesquisar);
        Pesquisar.setBounds(270, 250, 120, 39);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("NOME:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 90, 51, 24);

        Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/EXCLUIR_1.png"))); // NOI18N
        Excluir.setToolTipText("");
        Excluir.setBorderPainted(false);
        Excluir.setContentAreaFilled(false);
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(Excluir);
        Excluir.setBounds(400, 250, 110, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("SENHA:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 150, 51, 24);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("LOGIN:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 120, 51, 24);
        getContentPane().add(tfLogin);
        tfLogin.setBounds(170, 120, 250, 24);

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });
        getContentPane().add(tfNome);
        tfNome.setBounds(170, 90, 250, 24);
        getContentPane().add(tfSenha);
        tfSenha.setBounds(170, 150, 250, 22);

        SalvarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/SALVAR_2.png"))); // NOI18N
        SalvarUsuario.setBorderPainted(false);
        SalvarUsuario.setContentAreaFilled(false);
        SalvarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(SalvarUsuario);
        SalvarUsuario.setBounds(150, 250, 120, 40);

        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/x.png"))); // NOI18N
        Voltar.setBorderPainted(false);
        Voltar.setContentAreaFilled(false);
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(500, 10, 33, 29);

        cargo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Funcionario" }));
        getContentPane().add(cargo);
        cargo.setBounds(170, 180, 113, 21);

        transparencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/transparente.png"))); // NOI18N
        getContentPane().add(transparencia);
        transparencia.setBounds(30, 30, 500, 310);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/tela usuario.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 540, 350);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_LimparActionPerformed

    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed
        List<Usuario> lista;
        lista = (dao.listarUsuario());
        UsuarioTableModel itm = new UsuarioTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Usuario");
        if (objetoRetorno != null) {
            usuario = dao.pesquisarUsuarioId((Integer) objetoRetorno);
            tfNome.setText(usuario.getNome());
            tfLogin.setText(usuario.getLogin());
            tfSenha.setText(usuario.getSenha());

            Excluir.setEnabled(true);

        }
    }//GEN-LAST:event_PesquisarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        dao.excluirUsuario(usuario);
        JOptionPane.showMessageDialog(null, "Aluno excluído com sucesso!");
        limparCampos();
    }//GEN-LAST:event_ExcluirActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void SalvarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarUsuarioActionPerformed

        if (!tfNome.getText().equals("") && !tfLogin.getText().equals("")
                && !tfSenha.getText().equals("") && !cargo.getSelectedItem().equals("")) {
            usuario.setLogin(tfLogin.getText());
            usuario.setNome(tfNome.getText());
            usuario.setSenha(tfSenha.getText());
            usuario.setCargo(String.valueOf(cargo.getSelectedItem()));
            if (usuario.getId() != 0) {
                dao.editarUsuario(usuario);
                JOptionPane.showMessageDialog(null, "Usuário editado com sucesso!");
            } else {
                dao.salvarUsuario(usuario);
                JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso!");
            }
            limparCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Existem campos obrigatórios que não foram preenchidos!");
        }
    }//GEN-LAST:event_SalvarUsuarioActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastrarUsuario dialog = new CadastrarUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Limpar;
    private javax.swing.JButton Pesquisar;
    private javax.swing.JButton SalvarUsuario;
    private javax.swing.JButton Voltar;
    private javax.swing.JComboBox<String> cargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JTextField tfNome;
    private javax.swing.JPasswordField tfSenha;
    private javax.swing.JLabel transparencia;
    // End of variables declaration//GEN-END:variables
}
