/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author ALCIOMAR
 */
public class EscolhaDeAcao extends javax.swing.JFrame {

    /**
     * Creates new form EscolhaDeAcao
     */
    public EscolhaDeAcao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        CadastrarGabarito = new javax.swing.JButton();
        Resultados1 = new javax.swing.JButton();
        CadastrarUsuario = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        CadastrarAluno = new javax.swing.JButton();
        CorrigirGabarito = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setLayout(null);

        CadastrarGabarito.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CadastrarGabarito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/BOTAO CADASTRAR GABARITO.png"))); // NOI18N
        CadastrarGabarito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarGabaritoActionPerformed(evt);
            }
        });
        jPanel2.add(CadastrarGabarito);
        CadastrarGabarito.setBounds(100, 10, 180, 60);

        Resultados1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Resultados1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/BOTAO RESULTADO (1).png"))); // NOI18N
        Resultados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resultados1ActionPerformed(evt);
            }
        });
        jPanel2.add(Resultados1);
        Resultados1.setBounds(100, 240, 180, 59);

        CadastrarUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CadastrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/BOTAO CADASTRAR USUARIO.png"))); // NOI18N
        CadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(CadastrarUsuario);
        CadastrarUsuario.setBounds(100, 80, 180, 59);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/BOTAO SAIR.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(850, 10, 100, 60);

        CadastrarAluno.setText("CADASTRAR ALUNO");
        CadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarAlunoActionPerformed(evt);
            }
        });
        jPanel2.add(CadastrarAluno);
        CadastrarAluno.setBounds(110, 160, 160, 60);

        CorrigirGabarito.setText("CORRIGIR GABARITO");
        CorrigirGabarito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorrigirGabaritoActionPerformed(evt);
            }
        });
        jPanel2.add(CorrigirGabarito);
        CorrigirGabarito.setBounds(120, 330, 150, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/tela fvs principal.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(-20, 0, 980, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarGabaritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarGabaritoActionPerformed

        CadastrarGabarito cadastrarGabarito = new CadastrarGabarito(this, rootPaneCheckingEnabled);
        cadastrarGabarito.setVisible(true);


    }//GEN-LAST:event_CadastrarGabaritoActionPerformed

    private void Resultados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resultados1ActionPerformed
        CalcularResultado calcular = new CalcularResultado(this, rootPaneCheckingEnabled);
        calcular.setVisible(true);
    }//GEN-LAST:event_Resultados1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarAlunoActionPerformed
        CadastrarAluno aluno = new CadastrarAluno(this, rootPaneCheckingEnabled);
        aluno.setVisible(true);
    }//GEN-LAST:event_CadastrarAlunoActionPerformed

    private void CorrigirGabaritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorrigirGabaritoActionPerformed
        TelaCorrigirGabarito corrigirGabarito = new TelaCorrigirGabarito(this, rootPaneCheckingEnabled);
        corrigirGabarito.setVisible(true);
    }//GEN-LAST:event_CorrigirGabaritoActionPerformed

    private void CadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarUsuarioActionPerformed

        CadastrarUsuario cadastrarUsuario = new CadastrarUsuario(this, rootPaneCheckingEnabled);
        cadastrarUsuario.setVisible(true);
    }//GEN-LAST:event_CadastrarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolhaDeAcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolhaDeAcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolhaDeAcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolhaDeAcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolhaDeAcao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarAluno;
    private javax.swing.JButton CadastrarGabarito;
    private javax.swing.JButton CadastrarUsuario;
    private javax.swing.JButton CorrigirGabarito;
    private javax.swing.JButton Resultados1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
