/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Gabarito.Gabarito;
import Gabarito.GabaritoDAO;
import Gabarito.GabaritoTableModel;
import aluno.Aluno;
import aluno.AlunoDAO;
import aluno.AlunoTableModel;
import com.google.gson.Gson;
import corrigirGabarito.CorrigirDAO;
import corrigirGabarito.CorrigirGabarito;
import corrigirGabarito.CorrigirGabaritoTableModel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import util.LetraMaiuscula;

/**
 *
 * @author ALCIOMAR
 */
public class TelaCorrigirGabarito extends javax.swing.JDialog {

    CorrigirGabarito corrigir = new CorrigirGabarito();
    CorrigirDAO corrigirDAO = new CorrigirDAO();
    Gabarito gabarito = new Gabarito();
    GabaritoDAO dao = new GabaritoDAO();
    Aluno aluno = new Aluno();
    AlunoDAO alunoDAO = new AlunoDAO();

    Gson json = new Gson();

    public TelaCorrigirGabarito(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Excluir.setEnabled(false);

    }

    public void limparCampos() {
        util.Util.limparCamposJDialog(this);
        gabarito = new Gabarito();
        corrigir = new CorrigirGabarito();
        aluno = new Aluno();
        Excluir.setEnabled(false);
    }

    public void preencherCampos() {
        corrigir.setRespostaJSON(corrigir.getRespostaJSON().replace("\"", "").replace("[", "").replace("]", ""));
        corrigir.setResposta(corrigir.getRespostaJSON().split(","));
        tfProcessoSeletivo.setText(corrigir.getGabarito().getNomeGabarito());
        NotaDaRedacao.setText(String.valueOf(corrigir.getQtdAcertosRedacao()));
        tfNomeAluno.setText(corrigir.getAluno().getNome());
        qt01.setText(corrigir.getResposta()[0]);
        qt02.setText(corrigir.getResposta()[1]);
        qt03.setText(corrigir.getResposta()[2]);
        qt04.setText(corrigir.getResposta()[3]);
        qt05.setText(corrigir.getResposta()[4]);
        qt06.setText(corrigir.getResposta()[5]);
        qt08.setText(corrigir.getResposta()[6]);
        qt07.setText(corrigir.getResposta()[7]);
        qt09.setText(corrigir.getResposta()[8]);
        qt10.setText(corrigir.getResposta()[9]);
        qt11.setText(corrigir.getResposta()[10]);
        qt12.setText(corrigir.getResposta()[11]);
        qt13.setText(corrigir.getResposta()[12]);
        qt14.setText(corrigir.getResposta()[13]);
        qt15.setText(corrigir.getResposta()[14]);
        qt16.setText(corrigir.getResposta()[15]);
        qt17.setText(corrigir.getResposta()[16]);
        qt18.setText(corrigir.getResposta()[17]);
        qt19.setText(corrigir.getResposta()[18]);
        qt20.setText(corrigir.getResposta()[19]);
        qt21.setText(corrigir.getResposta()[20]);
        qt22.setText(corrigir.getResposta()[21]);
        qt23.setText(corrigir.getResposta()[22]);
        qt24.setText(corrigir.getResposta()[23]);
        qt25.setText(corrigir.getResposta()[24]);
        qt26.setText(corrigir.getResposta()[25]);
        qt27.setText(corrigir.getResposta()[26]);
        qt28.setText(corrigir.getResposta()[27]);
        qt29.setText(corrigir.getResposta()[28]);
        qt30.setText(corrigir.getResposta()[29]);
        qt31.setText(corrigir.getResposta()[30]);
        qt32.setText(corrigir.getResposta()[31]);
        qt33.setText(corrigir.getResposta()[32]);
        qt34.setText(corrigir.getResposta()[33]);
        qt35.setText(corrigir.getResposta()[34]);
        qt36.setText(corrigir.getResposta()[35]);
        qt37.setText(corrigir.getResposta()[36]);
        qt38.setText(corrigir.getResposta()[37]);
        qt39.setText(corrigir.getResposta()[38]);
        qt40.setText(corrigir.getResposta()[39]);
        qt41.setText(corrigir.getResposta()[40]);
        qt42.setText(corrigir.getResposta()[41]);
        qt43.setText(corrigir.getResposta()[42]);
        qt44.setText(corrigir.getResposta()[43]);
        qt45.setText(corrigir.getResposta()[44]);

    }

    /**
     * Creates new form CadastrarGabaritoo
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        qt15 = new javax.swing.JTextField();
        qt18 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        qt17 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        qt01 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        qt04 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        qt07 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        qt10 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        qt02 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        qt05 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        qt08 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        qt11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        qt13 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        qt03 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        qt14 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        qt16 = new javax.swing.JTextField();
        qt12 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        qt06 = new javax.swing.JTextField();
        qt09 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        qt20 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        qt21 = new javax.swing.JTextField();
        qt19 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        qt33 = new javax.swing.JTextField();
        qt34 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        qt37 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        qt40 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        qt36 = new javax.swing.JTextField();
        qt24 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        qt23 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        qt26 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        qt29 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        qt32 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        qt35 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        qt38 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        qt41 = new javax.swing.JTextField();
        qt39 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        qt30 = new javax.swing.JTextField();
        qt22 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        qt25 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        qt28 = new javax.swing.JTextField();
        qt27 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        qt31 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        qt45 = new javax.swing.JTextField();
        qt42 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        qt43 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        qt44 = new javax.swing.JTextField();
        SalvarGabarito = new javax.swing.JButton();
        LimparCampos = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        tfNomeAluno = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        PesquisarAluno = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        tfProcessoSeletivo = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        PesquisarProcessoSeletivo = new javax.swing.JButton();
        PesquisarGabarito = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        NotaDaRedacao = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(989, 779));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel15.setText("15º");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(390, 220, 34, 33);

        qt15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt15KeyTyped(evt);
            }
        });
        getContentPane().add(qt15);
        qt15.setBounds(430, 220, 44, 33);

        qt18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt18KeyTyped(evt);
            }
        });
        getContentPane().add(qt18);
        qt18.setBounds(830, 220, 44, 33);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel24.setText("17º");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(650, 220, 34, 33);

        qt17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt17KeyTyped(evt);
            }
        });
        getContentPane().add(qt17);
        qt17.setBounds(690, 220, 44, 33);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("1º");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 110, 34, 33);

        qt01.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                qt01FocusLost(evt);
            }
        });
        qt01.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qt01KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qt01KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt01KeyTyped(evt);
            }
        });
        getContentPane().add(qt01);
        qt01.setBounds(170, 110, 44, 33);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("4º");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(530, 110, 34, 33);

        qt04.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt04KeyTyped(evt);
            }
        });
        getContentPane().add(qt04);
        qt04.setBounds(570, 110, 44, 33);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("7º");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 170, 34, 33);

        qt07.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt07KeyTyped(evt);
            }
        });
        getContentPane().add(qt07);
        qt07.setBounds(170, 170, 44, 33);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("10º");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(530, 170, 34, 33);

        qt10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt10KeyTyped(evt);
            }
        });
        getContentPane().add(qt10);
        qt10.setBounds(570, 170, 44, 33);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("2º");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 110, 34, 33);

        qt02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qt02ActionPerformed(evt);
            }
        });
        qt02.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt02KeyTyped(evt);
            }
        });
        getContentPane().add(qt02);
        qt02.setBounds(290, 110, 44, 33);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("5º");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(650, 110, 34, 33);

        qt05.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt05KeyTyped(evt);
            }
        });
        getContentPane().add(qt05);
        qt05.setBounds(690, 110, 44, 33);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("8º");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(250, 170, 34, 33);

        qt08.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt08KeyTyped(evt);
            }
        });
        getContentPane().add(qt08);
        qt08.setBounds(290, 170, 44, 33);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("11º");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(650, 170, 34, 33);

        qt11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qt11ActionPerformed(evt);
            }
        });
        qt11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt11KeyTyped(evt);
            }
        });
        getContentPane().add(qt11);
        qt11.setBounds(690, 170, 44, 33);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel14.setText("13º");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(130, 220, 34, 33);

        qt13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt13KeyTyped(evt);
            }
        });
        getContentPane().add(qt13);
        qt13.setBounds(170, 220, 44, 33);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("3º");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 110, 34, 33);

        qt03.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt03KeyTyped(evt);
            }
        });
        getContentPane().add(qt03);
        qt03.setBounds(430, 110, 44, 33);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel13.setText("14º");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(250, 220, 34, 33);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel23.setText("18º");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(790, 220, 34, 33);

        qt14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt14KeyTyped(evt);
            }
        });
        getContentPane().add(qt14);
        qt14.setBounds(290, 220, 44, 33);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel30.setText("16º");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(530, 220, 34, 33);

        qt16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt16KeyTyped(evt);
            }
        });
        getContentPane().add(qt16);
        qt16.setBounds(570, 220, 44, 33);

        qt12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt12KeyTyped(evt);
            }
        });
        getContentPane().add(qt12);
        qt12.setBounds(830, 170, 44, 33);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("12º");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(790, 170, 34, 33);

        qt06.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt06KeyTyped(evt);
            }
        });
        getContentPane().add(qt06);
        qt06.setBounds(830, 110, 44, 33);

        qt09.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt09KeyTyped(evt);
            }
        });
        getContentPane().add(qt09);
        qt09.setBounds(430, 170, 44, 33);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("6º");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(790, 110, 34, 33);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("9º");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(390, 170, 34, 33);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel29.setText("20º");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(250, 280, 34, 33);

        qt20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt20KeyTyped(evt);
            }
        });
        getContentPane().add(qt20);
        qt20.setBounds(290, 280, 44, 33);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel28.setText("19º");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(130, 280, 34, 33);

        qt21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt21KeyTyped(evt);
            }
        });
        getContentPane().add(qt21);
        qt21.setBounds(430, 280, 44, 33);

        qt19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt19KeyTyped(evt);
            }
        });
        getContentPane().add(qt19);
        qt19.setBounds(170, 280, 44, 33);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel27.setText("21º");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(390, 280, 34, 33);

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel40.setText("34º");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(530, 390, 34, 33);

        qt33.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt33KeyTyped(evt);
            }
        });
        getContentPane().add(qt33);
        qt33.setBounds(430, 390, 44, 33);

        qt34.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt34KeyTyped(evt);
            }
        });
        getContentPane().add(qt34);
        qt34.setBounds(570, 390, 44, 33);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel35.setText("33º");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(390, 390, 34, 33);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel32.setText("37º");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(130, 440, 34, 33);

        qt37.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt37KeyTyped(evt);
            }
        });
        getContentPane().add(qt37);
        qt37.setBounds(170, 440, 44, 33);

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel44.setText("40º");
        getContentPane().add(jLabel44);
        jLabel44.setBounds(530, 440, 34, 33);

        qt40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qt40ActionPerformed(evt);
            }
        });
        qt40.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt40KeyTyped(evt);
            }
        });
        getContentPane().add(qt40);
        qt40.setBounds(570, 440, 44, 33);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel16.setText("27º");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(390, 340, 34, 33);

        qt36.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt36KeyTyped(evt);
            }
        });
        getContentPane().add(qt36);
        qt36.setBounds(830, 390, 44, 33);

        qt24.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt24KeyTyped(evt);
            }
        });
        getContentPane().add(qt24);
        qt24.setBounds(830, 280, 44, 33);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel19.setText("24º");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(790, 280, 34, 33);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel39.setText("36º");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(790, 390, 34, 33);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel22.setText("23º");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(650, 280, 34, 33);

        qt23.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt23KeyTyped(evt);
            }
        });
        getContentPane().add(qt23);
        qt23.setBounds(690, 280, 44, 33);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel18.setText("26º");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(250, 340, 34, 33);

        qt26.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt26KeyTyped(evt);
            }
        });
        getContentPane().add(qt26);
        qt26.setBounds(290, 340, 44, 33);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel21.setText("29º");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(650, 340, 34, 33);

        qt29.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt29KeyTyped(evt);
            }
        });
        getContentPane().add(qt29);
        qt29.setBounds(690, 340, 44, 33);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel36.setText("32º");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(250, 390, 34, 33);

        qt32.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt32KeyTyped(evt);
            }
        });
        getContentPane().add(qt32);
        qt32.setBounds(290, 390, 44, 33);

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel41.setText("35º");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(650, 390, 34, 33);

        qt35.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt35KeyTyped(evt);
            }
        });
        getContentPane().add(qt35);
        qt35.setBounds(690, 390, 44, 33);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel34.setText("38º");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(250, 440, 34, 33);

        qt38.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt38KeyTyped(evt);
            }
        });
        getContentPane().add(qt38);
        qt38.setBounds(290, 440, 44, 33);

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel45.setText("41º");
        getContentPane().add(jLabel45);
        jLabel45.setBounds(650, 440, 34, 33);

        qt41.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt41KeyTyped(evt);
            }
        });
        getContentPane().add(qt41);
        qt41.setBounds(690, 440, 44, 33);

        qt39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qt39ActionPerformed(evt);
            }
        });
        qt39.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt39KeyTyped(evt);
            }
        });
        getContentPane().add(qt39);
        qt39.setBounds(430, 440, 44, 33);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel26.setText("30º");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(790, 340, 34, 33);

        qt30.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt30KeyTyped(evt);
            }
        });
        getContentPane().add(qt30);
        qt30.setBounds(830, 340, 44, 33);

        qt22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt22KeyTyped(evt);
            }
        });
        getContentPane().add(qt22);
        qt22.setBounds(570, 280, 44, 33);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel20.setText("22º");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(530, 280, 34, 33);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel17.setText("25º");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(130, 340, 34, 33);

        qt25.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt25KeyTyped(evt);
            }
        });
        getContentPane().add(qt25);
        qt25.setBounds(170, 340, 44, 33);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel25.setText("28º");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(530, 340, 34, 33);

        qt28.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt28KeyTyped(evt);
            }
        });
        getContentPane().add(qt28);
        qt28.setBounds(570, 340, 44, 33);

        qt27.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt27KeyTyped(evt);
            }
        });
        getContentPane().add(qt27);
        qt27.setBounds(430, 340, 44, 33);

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel42.setText("31º");
        getContentPane().add(jLabel42);
        jLabel42.setBounds(130, 390, 34, 33);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel31.setText("39º");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(390, 440, 34, 33);

        qt31.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt31KeyTyped(evt);
            }
        });
        getContentPane().add(qt31);
        qt31.setBounds(170, 390, 44, 33);

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel38.setText("45º");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(390, 490, 34, 33);

        qt45.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt45KeyTyped(evt);
            }
        });
        getContentPane().add(qt45);
        qt45.setBounds(430, 490, 44, 33);

        qt42.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt42KeyTyped(evt);
            }
        });
        getContentPane().add(qt42);
        qt42.setBounds(830, 440, 44, 33);

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel43.setText("42º");
        getContentPane().add(jLabel43);
        jLabel43.setBounds(790, 440, 34, 33);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel37.setText("43º");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(130, 490, 34, 33);

        qt43.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt43KeyTyped(evt);
            }
        });
        getContentPane().add(qt43);
        qt43.setBounds(170, 490, 44, 33);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel33.setText("44º");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(250, 490, 34, 33);

        qt44.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qt44KeyTyped(evt);
            }
        });
        getContentPane().add(qt44);
        qt44.setBounds(290, 490, 44, 33);

        SalvarGabarito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/SALVAR_1.png"))); // NOI18N
        SalvarGabarito.setBorderPainted(false);
        SalvarGabarito.setContentAreaFilled(false);
        SalvarGabarito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarGabaritoActionPerformed(evt);
            }
        });
        getContentPane().add(SalvarGabarito);
        SalvarGabarito.setBounds(790, 590, 100, 50);

        LimparCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/limpar.png"))); // NOI18N
        LimparCampos.setBorderPainted(false);
        LimparCampos.setContentAreaFilled(false);
        LimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparCamposActionPerformed(evt);
            }
        });
        getContentPane().add(LimparCampos);
        LimparCampos.setBounds(680, 590, 100, 50);

        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/voltar.png"))); // NOI18N
        Voltar.setToolTipText("");
        Voltar.setBorderPainted(false);
        Voltar.setContentAreaFilled(false);
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(570, 590, 100, 50);

        jLabel46.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel46.setText("NOME ALUNO");
        getContentPane().add(jLabel46);
        jLabel46.setBounds(130, 560, 160, 26);

        tfNomeAluno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfNomeAluno.setEnabled(false);
        tfNomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeAlunoActionPerformed(evt);
            }
        });
        tfNomeAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNomeAlunoKeyTyped(evt);
            }
        });
        getContentPane().add(tfNomeAluno);
        tfNomeAluno.setBounds(130, 590, 274, 34);

        jLabel48.setFont(new java.awt.Font("Geometr415 Blk BT", 1, 36)); // NOI18N
        jLabel48.setText("CORRIGIR GABARITO");
        getContentPane().add(jLabel48);
        jLabel48.setBounds(330, 20, 400, 44);

        PesquisarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/PESQUISAR.png"))); // NOI18N
        PesquisarAluno.setBorderPainted(false);
        PesquisarAluno.setContentAreaFilled(false);
        PesquisarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(PesquisarAluno);
        PesquisarAluno.setBounds(410, 590, 70, 39);

        Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/EXCLUIR.png"))); // NOI18N
        Excluir.setBorderPainted(false);
        Excluir.setContentAreaFilled(false);
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(Excluir);
        Excluir.setBounds(730, 660, 100, 50);

        tfProcessoSeletivo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfProcessoSeletivo.setEnabled(false);
        tfProcessoSeletivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProcessoSeletivoActionPerformed(evt);
            }
        });
        tfProcessoSeletivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfProcessoSeletivoKeyTyped(evt);
            }
        });
        getContentPane().add(tfProcessoSeletivo);
        tfProcessoSeletivo.setBounds(130, 670, 274, 34);

        jLabel47.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel47.setText("PROCESSO SELETIVO");
        getContentPane().add(jLabel47);
        jLabel47.setBounds(130, 630, 160, 26);

        PesquisarProcessoSeletivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/PESQUISAR.png"))); // NOI18N
        PesquisarProcessoSeletivo.setBorderPainted(false);
        PesquisarProcessoSeletivo.setContentAreaFilled(false);
        PesquisarProcessoSeletivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarProcessoSeletivoActionPerformed(evt);
            }
        });
        getContentPane().add(PesquisarProcessoSeletivo);
        PesquisarProcessoSeletivo.setBounds(410, 670, 70, 39);

        PesquisarGabarito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/PESQUISAR2.png"))); // NOI18N
        PesquisarGabarito.setBorderPainted(false);
        PesquisarGabarito.setContentAreaFilled(false);
        PesquisarGabarito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarGabaritoActionPerformed(evt);
            }
        });
        getContentPane().add(PesquisarGabarito);
        PesquisarGabarito.setBounds(620, 660, 100, 50);

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel49.setText("NOTA DA REDAÇÃO");
        getContentPane().add(jLabel49);
        jLabel49.setBounds(497, 490, 110, 34);

        NotaDaRedacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NotaDaRedacaoKeyTyped(evt);
            }
        });
        getContentPane().add(NotaDaRedacao);
        NotaDaRedacao.setBounds(610, 490, 83, 34);

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/TRANPARENTE CONTORNO.png"))); // NOI18N
        getContentPane().add(jLabel51);
        jLabel51.setBounds(100, 90, 840, 630);

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/tela gabarito_1.png"))); // NOI18N
        getContentPane().add(jLabel50);
        jLabel50.setBounds(0, 0, 990, 740);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void qt15KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt15KeyTyped
        int ascii = evt.getKeyChar();
        qt15.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt16.requestFocus();
        }
        if (qt15.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt15KeyTyped

    private void qt18KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt18KeyTyped
        int ascii = evt.getKeyChar();
        qt18.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt19.requestFocus();
        }
        if (qt18.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt18KeyTyped

    private void qt17KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt17KeyTyped
        int ascii = evt.getKeyChar();
        qt17.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt18.requestFocus();
        }
        if (qt17.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt17KeyTyped

    private void qt01FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qt01FocusLost

    }//GEN-LAST:event_qt01FocusLost

    private void qt01KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt01KeyPressed

    }//GEN-LAST:event_qt01KeyPressed

    private void qt01KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt01KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_qt01KeyReleased

    private void qt01KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt01KeyTyped

        int ascii = evt.getKeyChar();
        qt01.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt02.requestFocus();
        }
        if (qt01.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt01KeyTyped

    private void qt04KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt04KeyTyped
        int ascii = evt.getKeyChar();
        qt04.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt05.requestFocus();
        }
        if (qt04.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt04KeyTyped

    private void qt07KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt07KeyTyped
        int ascii = evt.getKeyChar();
        qt07.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt08.requestFocus();
        }
        if (qt07.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt07KeyTyped

    private void qt10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt10KeyTyped
        int ascii = evt.getKeyChar();
        qt10.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt11.requestFocus();
        }
        if (qt10.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt10KeyTyped

    private void qt02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qt02ActionPerformed

    }//GEN-LAST:event_qt02ActionPerformed

    private void qt02KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt02KeyTyped
        int ascii = evt.getKeyChar();
        qt02.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt03.requestFocus();
        }
        if (qt02.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt02KeyTyped

    private void qt05KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt05KeyTyped
        int ascii = evt.getKeyChar();
        qt05.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt06.requestFocus();
        }
        if (qt05.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt05KeyTyped

    private void qt08KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt08KeyTyped
        int ascii = evt.getKeyChar();
        qt08.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt09.requestFocus();
        }
        if (qt08.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt08KeyTyped

    private void qt11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qt11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qt11ActionPerformed

    private void qt11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt11KeyTyped
        int ascii = evt.getKeyChar();
        qt11.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt12.requestFocus();
        }
        if (qt11.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt11KeyTyped

    private void qt13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt13KeyTyped
        int ascii = evt.getKeyChar();
        qt13.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt14.requestFocus();
        }
        if (qt13.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt13KeyTyped

    private void qt03KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt03KeyTyped
        int ascii = evt.getKeyChar();
        qt03.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt04.requestFocus();
        }
        if (qt03.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt03KeyTyped

    private void qt14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt14KeyTyped
        int ascii = evt.getKeyChar();
        qt14.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt15.requestFocus();
        }
        if (qt14.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt14KeyTyped

    private void qt16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt16KeyTyped
        int ascii = evt.getKeyChar();
        qt16.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt17.requestFocus();
        }
        if (qt16.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt16KeyTyped

    private void qt12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt12KeyTyped
        int ascii = evt.getKeyChar();
        qt12.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt13.requestFocus();
        }
        if (qt12.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt12KeyTyped

    private void qt06KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt06KeyTyped
        int ascii = evt.getKeyChar();
        qt06.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt07.requestFocus();
        }
        if (qt06.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt06KeyTyped

    private void qt09KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt09KeyTyped
        int ascii = evt.getKeyChar();
        qt09.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt10.requestFocus();
        }
        if (qt09.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt09KeyTyped

    private void qt20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt20KeyTyped
        int ascii = evt.getKeyChar();
        qt20.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt21.requestFocus();
        }
        if (qt20.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt20KeyTyped

    private void qt21KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt21KeyTyped
        int ascii = evt.getKeyChar();
        qt21.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt22.requestFocus();
        }
        if (qt21.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt21KeyTyped

    private void qt19KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt19KeyTyped
        int ascii = evt.getKeyChar();
        qt19.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt20.requestFocus();
        }
        if (qt19.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt19KeyTyped

    private void qt33KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt33KeyTyped
        int ascii = evt.getKeyChar();
        qt33.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt34.requestFocus();
        }
        if (qt33.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt33KeyTyped

    private void qt34KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt34KeyTyped
        int ascii = evt.getKeyChar();
        qt34.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt35.requestFocus();
        }
        if (qt34.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt34KeyTyped

    private void qt37KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt37KeyTyped
        int ascii = evt.getKeyChar();
        qt37.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt38.requestFocus();
        }
        if (qt37.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt37KeyTyped

    private void qt40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qt40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qt40ActionPerformed

    private void qt40KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt40KeyTyped
        int ascii = evt.getKeyChar();
        qt40.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt41.requestFocus();
        }
        if (qt40.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt40KeyTyped

    private void qt36KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt36KeyTyped
        int ascii = evt.getKeyChar();
        qt36.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt37.requestFocus();
        }
        if (qt36.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt36KeyTyped

    private void qt24KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt24KeyTyped
        int ascii = evt.getKeyChar();
        qt24.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt25.requestFocus();
        }
        if (qt24.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt24KeyTyped

    private void qt23KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt23KeyTyped
        int ascii = evt.getKeyChar();
        qt23.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt24.requestFocus();
        }
        if (qt23.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt23KeyTyped

    private void qt26KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt26KeyTyped
        int ascii = evt.getKeyChar();
        qt26.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt27.requestFocus();
        }
        if (qt26.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt26KeyTyped

    private void qt29KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt29KeyTyped
        int ascii = evt.getKeyChar();
        qt29.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt30.requestFocus();
        }
        if (qt29.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt29KeyTyped

    private void qt32KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt32KeyTyped
        int ascii = evt.getKeyChar();
        qt32.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt33.requestFocus();
        }
        if (qt32.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt32KeyTyped

    private void qt35KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt35KeyTyped
        int ascii = evt.getKeyChar();
        qt35.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt36.requestFocus();
        }
        if (qt35.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt35KeyTyped

    private void qt38KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt38KeyTyped
        int ascii = evt.getKeyChar();
        qt38.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt39.requestFocus();
        }
        if (qt38.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt38KeyTyped

    private void qt41KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt41KeyTyped
        int ascii = evt.getKeyChar();
        qt41.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt42.requestFocus();
        }
        if (qt41.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt41KeyTyped

    private void qt39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qt39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qt39ActionPerformed

    private void qt39KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt39KeyTyped
        int ascii = evt.getKeyChar();
        qt39.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt40.requestFocus();
        }
        if (qt39.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt39KeyTyped

    private void qt30KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt30KeyTyped
        int ascii = evt.getKeyChar();
        qt30.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt31.requestFocus();
        }
        if (qt30.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt30KeyTyped

    private void qt22KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt22KeyTyped
        int ascii = evt.getKeyChar();
        qt22.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt23.requestFocus();
        }
        if (qt22.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt22KeyTyped

    private void qt25KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt25KeyTyped
        int ascii = evt.getKeyChar();
        qt25.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt26.requestFocus();
        }
        if (qt25.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt25KeyTyped

    private void qt28KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt28KeyTyped
        int ascii = evt.getKeyChar();
        qt28.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt29.requestFocus();
        }
        if (qt28.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt28KeyTyped

    private void qt27KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt27KeyTyped
        int ascii = evt.getKeyChar();
        qt27.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt28.requestFocus();
        }
        if (qt27.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt27KeyTyped

    private void qt31KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt31KeyTyped
        int ascii = evt.getKeyChar();
        qt31.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt32.requestFocus();
        }
        if (qt31.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt31KeyTyped

    private void qt45KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt45KeyTyped
        int ascii = evt.getKeyChar();
        qt45.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            NotaDaRedacao.requestFocus();
        }
        if (qt45.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt45KeyTyped

    private void qt42KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt42KeyTyped
        int ascii = evt.getKeyChar();
        qt42.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt43.requestFocus();
        }
        if (qt42.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt42KeyTyped

    private void qt43KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt43KeyTyped
        int ascii = evt.getKeyChar();
        qt43.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt44.requestFocus();
        }
        if (qt43.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt43KeyTyped

    private void qt44KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qt44KeyTyped
        int ascii = evt.getKeyChar();
        qt44.setDocument(new LetraMaiuscula());
        if (!(ascii >= 65 && ascii <= 69) && !(ascii >= 97 && ascii <= 101) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            qt45.requestFocus();
        }
        if (qt44.getText().length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_qt44KeyTyped

    private void SalvarGabaritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarGabaritoActionPerformed

        preencherArray();

        corrigir.setRespostaJSON(json.toJson(corrigir.getResposta()));
        corrigir.setQtdAcertosRedacao(Integer.parseInt(NotaDaRedacao.getText()));
        if (corrigir.getId() == 0) {
            corrigirDAO.salvarCorrigirGabarito(corrigir);
            JOptionPane.showMessageDialog(null, "Gabarito Cadastrado com Sucesso!");
        } else {
            corrigirDAO.editarCorrigirGabarito(corrigir);
            JOptionPane.showMessageDialog(null, "Gabarito Editado com Sucesso!");
        }
        limparCampos();

    }//GEN-LAST:event_SalvarGabaritoActionPerformed

    private void LimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparCamposActionPerformed

        limparCampos();
    }//GEN-LAST:event_LimparCamposActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed

        EscolhaDeAcao escolhaDeAcao = new EscolhaDeAcao();
        escolhaDeAcao.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void tfNomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeAlunoActionPerformed

    private void tfNomeAlunoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeAlunoKeyTyped

    }//GEN-LAST:event_tfNomeAlunoKeyTyped

    private void PesquisarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarAlunoActionPerformed

        List<Aluno> lista;
        lista = (alunoDAO.listarAluno());
        AlunoTableModel itm = new AlunoTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Aluno");
        if (objetoRetorno != null) {
            aluno = alunoDAO.pesquisarAlunoId((Integer) objetoRetorno);
            tfNomeAluno.setText(aluno.getNome());
            corrigir.setAluno(aluno);
            Excluir.setEnabled(true);

        }
    }//GEN-LAST:event_PesquisarAlunoActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        corrigirDAO.excluirCorrigirGabarito(corrigir);
        JOptionPane.showMessageDialog(null, "Gabarito excluído com sucesso!");
        limparCampos();
    }//GEN-LAST:event_ExcluirActionPerformed

    private void tfProcessoSeletivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProcessoSeletivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProcessoSeletivoActionPerformed

    private void tfProcessoSeletivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfProcessoSeletivoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProcessoSeletivoKeyTyped

    private void PesquisarProcessoSeletivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarProcessoSeletivoActionPerformed
        List<Gabarito> lista;
        lista = (dao.listarGabarito());
        GabaritoTableModel itm = new GabaritoTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Gabarito");
        if (objetoRetorno != null) {
            gabarito = dao.pesquisarGabarito((Integer) objetoRetorno);
            tfProcessoSeletivo.setText(gabarito.getNomeGabarito());
            corrigir.setGabarito(gabarito);

        }


    }//GEN-LAST:event_PesquisarProcessoSeletivoActionPerformed

    private void PesquisarGabaritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarGabaritoActionPerformed
        List<CorrigirGabarito> lista;
        lista = (corrigirDAO.listarCorrigirGabarito());
        CorrigirGabaritoTableModel itm = new CorrigirGabaritoTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Corrigir Gabarito");
        if (objetoRetorno != null) {
            corrigir = corrigirDAO.pesquisarCorrigirGabarito((Integer) objetoRetorno);
            preencherCampos();
            Excluir.setEnabled(true);

        }

    }//GEN-LAST:event_PesquisarGabaritoActionPerformed

    private void NotaDaRedacaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NotaDaRedacaoKeyTyped
        int ascii = evt.getKeyChar();
        if (!(ascii >= 48 && ascii <= 57) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        } else {
            NotaDaRedacao.requestFocus();
        }

    }//GEN-LAST:event_NotaDaRedacaoKeyTyped

    public void verificarCampos(int posicao, JTextField tf) {

        if (tf.getText().isEmpty()) {
            corrigir.getResposta()[posicao] = "nula";
        } else {
            corrigir.getResposta()[posicao] = tf.getText().toUpperCase();
        }

    }

    public void preencherArray() {
        verificarCampos(0, qt01);
        verificarCampos(1, qt02);
        verificarCampos(2, qt03);
        verificarCampos(3, qt04);
        verificarCampos(4, qt05);
        verificarCampos(5, qt06);
        verificarCampos(6, qt07);
        verificarCampos(7, qt08);
        verificarCampos(8, qt09);
        verificarCampos(9, qt10);
        verificarCampos(10, qt11);
        verificarCampos(11, qt12);
        verificarCampos(12, qt13);
        verificarCampos(13, qt14);
        verificarCampos(14, qt15);
        verificarCampos(15, qt16);
        verificarCampos(16, qt17);
        verificarCampos(17, qt18);
        verificarCampos(18, qt19);
        verificarCampos(19, qt20);
        verificarCampos(20, qt21);
        verificarCampos(21, qt22);
        verificarCampos(22, qt23);
        verificarCampos(23, qt24);
        verificarCampos(24, qt25);
        verificarCampos(25, qt26);
        verificarCampos(26, qt27);
        verificarCampos(27, qt28);
        verificarCampos(28, qt29);
        verificarCampos(29, qt30);
        verificarCampos(30, qt31);
        verificarCampos(31, qt32);
        verificarCampos(32, qt33);
        verificarCampos(33, qt34);
        verificarCampos(34, qt35);
        verificarCampos(35, qt36);
        verificarCampos(36, qt37);
        verificarCampos(37, qt38);
        verificarCampos(38, qt39);
        verificarCampos(39, qt40);
        verificarCampos(40, qt41);
        verificarCampos(41, qt42);
        verificarCampos(42, qt43);
        verificarCampos(43, qt44);
        verificarCampos(44, qt45);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCorrigirGabarito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCorrigirGabarito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCorrigirGabarito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCorrigirGabarito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCorrigirGabarito dialog = new TelaCorrigirGabarito(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Excluir;
    private javax.swing.JButton LimparCampos;
    private javax.swing.JTextField NotaDaRedacao;
    private javax.swing.JButton PesquisarAluno;
    private javax.swing.JButton PesquisarGabarito;
    private javax.swing.JButton PesquisarProcessoSeletivo;
    private javax.swing.JButton SalvarGabarito;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField qt01;
    private javax.swing.JTextField qt02;
    private javax.swing.JTextField qt03;
    private javax.swing.JTextField qt04;
    private javax.swing.JTextField qt05;
    private javax.swing.JTextField qt06;
    private javax.swing.JTextField qt07;
    private javax.swing.JTextField qt08;
    private javax.swing.JTextField qt09;
    private javax.swing.JTextField qt10;
    private javax.swing.JTextField qt11;
    private javax.swing.JTextField qt12;
    private javax.swing.JTextField qt13;
    private javax.swing.JTextField qt14;
    private javax.swing.JTextField qt15;
    private javax.swing.JTextField qt16;
    private javax.swing.JTextField qt17;
    private javax.swing.JTextField qt18;
    private javax.swing.JTextField qt19;
    private javax.swing.JTextField qt20;
    private javax.swing.JTextField qt21;
    private javax.swing.JTextField qt22;
    private javax.swing.JTextField qt23;
    private javax.swing.JTextField qt24;
    private javax.swing.JTextField qt25;
    private javax.swing.JTextField qt26;
    private javax.swing.JTextField qt27;
    private javax.swing.JTextField qt28;
    private javax.swing.JTextField qt29;
    private javax.swing.JTextField qt30;
    private javax.swing.JTextField qt31;
    private javax.swing.JTextField qt32;
    private javax.swing.JTextField qt33;
    private javax.swing.JTextField qt34;
    private javax.swing.JTextField qt35;
    private javax.swing.JTextField qt36;
    private javax.swing.JTextField qt37;
    private javax.swing.JTextField qt38;
    private javax.swing.JTextField qt39;
    private javax.swing.JTextField qt40;
    private javax.swing.JTextField qt41;
    private javax.swing.JTextField qt42;
    private javax.swing.JTextField qt43;
    private javax.swing.JTextField qt44;
    private javax.swing.JTextField qt45;
    private javax.swing.JTextField tfNomeAluno;
    private javax.swing.JTextField tfProcessoSeletivo;
    // End of variables declaration//GEN-END:variables
}
